- id: doi:10.5194/gmd-15-4105-2022
  title: Simulation, precursor analysis and targeted observation sensitive area identification for two types of ENSO using ENSO-MC v1.0
  tags: ENSO, Prediction
  authors:
    - Bin Mu
    - Yuehan Cui
    - Shijin Yuan
    - Bo Qin
  publisher: European Geosciences Union
  date: '2022-05-25'
  link: https://gmd.copernicus.org/articles/15/4105/2022/
  image: https://gmd.copernicus.org/articles/15/4105/2022/gmd-15-4105-2022-avatar-web.png

- id: doi:10.5194/gmd-14-6977-2021
  title: >
    ENSO-ASC 1.0.0: ENSO deep learning forecast model with a multivariate air–sea coupler
  tags: ENSO, deep learning, Forecast Model
  authors:
    - Bin Mu
    - Bo Qin
    - Shijin Yuan
  publisher: European Geosciences Union
  date: '2021-11-17'
  link: https://gmd.copernicus.org/articles/14/6977/2021/
  image: https://gmd.copernicus.org/articles/14/6977/2021/gmd-14-6977-2021-avatar-thumb150.png
  
- id: doi:10.1007/s00500-021-06639-8
  title: Feature extraction-based intelligent algorithm framework with neural network for solving conditional nonlinear optimal perturbation
  tags: ENSO, intelligent algorithm
  authors:
    - Shijin Yuan
    - Huazhen Zhang
    - Yaxuan Liu
    - Bin Mu
  publisher: Springer Link
  date: '2022-01-29'
  link: https://link.springer.com/article/10.1007/s00500-021-06639-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00500-021-06639-8/MediaObjects/500_2021_6639_Fig1_HTML.png?as=webp
  
- id: doi:10.1155/2022/6141966
  title: The NAO Variability Prediction and Forecasting with Multiple Time Scales Driven by ENSO Using Machine Learning Approaches
  tags: ENSO, typhoon, Machine Learning
  authors:
    - Bin Mu
    - Jing Li
    - Shijin Yuan
    - Xiaodan Luo
  publisher: Wiley
  date: '2022-04-15'
  link: https://onlinelibrary.wiley.com/doi/10.1155/2022/6141966
  image: https://onlinelibrary.wiley.com/cms/asset/614882d6-a3c1-4c8b-834a-5003f3faba0f/cone6141966-fig-0004-m.jpg

- id: doi:10.5194/npg-2020-27
  title: Optimal Precursors Identification for North Atlantic Oscillation using CESM and CNOP Method
  tags: ENSO, CNOP
  authors:
    - Bin Mu
    - Jing Li
    - Shijin Yuan
    - Xiaodan Luo
    - Guokun Dai
  publisher: European Geosciences Union
  date: '2020-07-01'
  link: https://npg.copernicus.org/preprints/npg-2020-27/
  image: https://onlinelibrary.wiley.com/cms/asset/782d5b32-7595-46c5-9419-ee3c23cef6b3/scpr3215039-fig-0002-m.png

- id: doi:10.46267/j.1006-8775.2022.010
  title: >
    Ensemble Forecast for Tropical Cyclone Based on CNOP-P Method: A Case Study of WRF Model and Two Typhoons
  tags: ENSO, typhoon, CNOP
  authors:
    - Yuan Shijin
    - Shi Bo
    - Zhao Zijun
    - Mu Bin
    - Zhou Feifan
    - Duan Wansuo
  publisher: Journal of Tropical Meteorology
  date: '2022-06-10'
  link: https://jtm.itmm.org.cn/en/article/doi/10.46267/j.1006-8775.2022.010
  image: https://jtm.itmm.org.cn/fileRDQXXB_EN/journal/article/rdqxxben/2022/2/jotm-28-2-121-2.jpg

- id: doi:10.5194/gmd-14-6977-2021
  title: >
    ENSO-ASC 1.0.0: ENSO Deep Learning Forecast Model with a Multivariate Air-Sea Coupler
  tags: ENSO, deep learning, Forecast Model
  authors:
    - Bin Mu
    - Bo Qin
    - Shijin Yuan
  publisher: European Geosciences Union
  date: '2021-11-17'
  link: https://gmd.copernicus.org/articles/14/6977/2021/
  image: https://gmd.copernicus.org/articles/14/6977/2021/gmd-14-6977-2021-avatar-thumb150.png

- id: doi:10.3390/a14030083
  title: Typhoon Intensity Forecasting Based on LSTM Using the Rolling Forecast Method
  tags: typhoon, Intensity Forecasting
  authors:
    - Shijin Yuan
    - Cheng Wang
    - Bin Mu
    - Feifan Zhou
    - Wansuo Duan
  publisher: Multidisciplinary Digital Publishing Institute
  date: '2021-03-04'
  link: https://www.mdpi.com/1999-4893/14/3/83
  image: https://www.mdpi.com/algorithms/algorithms-14-00083/article_deploy/html/images/algorithms-14-00083-g010-550.jpg